cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'

brew 'ack'
brew 'tree'
brew 'coreutils'
brew 'rbenv'
brew 'git'
brew 'git-extras'
brew 'tig'
brew 'hub'
brew 'imagemagick --with-webp'
brew 'mysql'
brew 'nvm'
brew 'gradle'
brew 'htop'
brew 'z'
brew 'wget'
brew 'php'

cask 'java'
cask 'firefox'
cask 'google-chrome'
cask 'seashore'
cask 'slack'
cask 'vlc'
cask 'iterm2'
cask 'google-backup-and-sync'
cask 'spectacle'
cask 'imageoptim'
cask 'evernote'
cask 'spotify'
cask 'ngrok'
cask 'docker'
